export default {
  zombieBounce: 'zombie-bounce',
  zombieWalk: 'zombie-walk',
  zombieRun: 'zombie-run',
  zombieFall: 'zombie-fall',
  zombieDamage: 'zombie-damage',
  zombieDie: 'zombie-die',
  zombieStun: 'zombie-stun',
  zombieAttack: 'zombie-attack',
  shotBlastExplode: 'shot-blast-explode',
  shotBlastGreenExplode: 'shot-blast-green-explode',
  shotBlastBottleExplode: 'shot-blast-bottle-explode',
  shotBlastDirtExplode: 'shot-blast-dirt-explode',
  bottle1Explode: 'bottle1-explode',
  popWhitePop: 'pop-white-pop',
  frames: {
    zombieBounce: [0, 1, 2, 3],
    zombieWalk: [6, 7, 8, 9],
    zombieRun: [12, 13, 14, 15, 16, 17],
    zombieFall: [18, 19, 20, 21],
    zombieDamage: [24, 25, 26, 26],
    zombieDie: [26, 24, 24, 24],
    zombieStun: [30, 31, 32, 33],
    zombieAttack: [36, 36, 36, 36, 36, 37, 38],
    shotBlastExplode: [0, 1, 1, 2, 2, 3],
    shotBlastGreenExplode: [0, 1, 1, 2, 2, 3],
    shotBlastBottleExplode: [0, 1, 1, 2, 2, 3],
    shotBlastDirtExplode: [0, 1, 1, 2, 2, 3],
    bottle1Explode: [0, 1, 2, 3, 4, 5, 6],
    popWhitePop: [2, 0, 1, 3],
  },
  frameRates: {
    zombieBounce: 8,
    zombieWalk: 6,
    zombieRun: 12,
    zombieFall: 15,
    zombieDamage: 10,
    zombieDie: 15,
    zombieStun: 8,
    zombieAttack: 10,
    shotBlastExplode: 20,
    shotBlastGreenExplode: 20,
    shotBlastBottleExplode: 15,
    shotBlastDirtExplode: 20,
    bottle1Explode: 13,
    popWhitePop: 12,
  },
};
