export default {
  grayZombie: 'gray-zombie',
  greenZombie: 'green-zombie',
  lightGreenZombie: 'light-green-zombie',
  redZombie: 'red-zombie',
  grass: 'grass',
  loading: 'loading',
  start: 'start',
  return: 'return',
  files: {
    grayZombie: 'assets/images/zombie-gray.png',
    greenZombie: 'assets/images/zombie-green.png',
    lightGreenZombie: 'assets/images/zombie-light-green.png',
    redZombie: 'assets/images/zombie-red.png',
    grass: 'assets/images/grass.png',
    loading: 'assets/images/loading.png',
    start: 'assets/images/start.png',
    return: 'assets/images/return.png',
  },
};
