export default {
  grayZombie: 'gray-zombie',
  greenZombie: 'green-zombie',
  lightGreenZombie: 'light-green-zombie',
  redZombie: 'red-zombie',
  grass: 'grass',
  loading: 'loading',
  start: 'start',
  return: 'return',
  hudItemBorder: 'hud-item-border',
  hudMessageBorder: 'hud-message-border',
  heart: 'heart',
  skull: 'skull',
  goldCoin: 'gold-coin',
  watch: 'watch',
  health: 'health',
  files: {
    grayZombie: 'assets/images/zombie-gray.png',
    greenZombie: 'assets/images/zombie-green.png',
    lightGreenZombie: 'assets/images/zombie-light-green.png',
    redZombie: 'assets/images/zombie-red.png',
    grass: 'assets/images/grass.png',
    loading: 'assets/images/loading.png',
    start: 'assets/images/start.png',
    return: 'assets/images/return.png',
    hudItemBorder: 'assets/images/hud-item-border.png',
    hudMessageBorder: 'assets/images/hud-message-border.png',
    heart: 'assets/images/heart.png',
    skull: 'assets/images/skull.png',
    goldCoin: 'assets/images/gold-coin.png',
    watch: 'assets/images/watch.png',
    health:  'assets/images/health.png',
  },
  frames: {
    healthFull: 0,
    healthEmpty: 1,
  },
};
