export default {
  demo: {
    name: 'lesson-demo',
    stage1: 'demo-1',
  },
  basicVocab: {
    name: 'lesson-basic-vocab',
    stage1: 'basic-vocab-1',
    stage2: 'basic-vocab-2',
    stage3: 'basic-vocab-3',
    stage4: 'basic-vocab-4',
    review: 'basic-vocab-review',
  },
  numbers1: {
    name: 'lesson-numbers-1',
    stage1: 'numbers-1-1',
    stage2: 'numbers-1-2',
    stage3: 'numbers-1-3',
    review: 'numbers-1-review',
  },
  nouns1: {
    name: 'lesson-nouns-1',
    stage1: 'nouns-1-1',
    stage2: 'nouns-1-2',
    stage3: 'nouns-1-3',
    stage4: 'nouns-1-4',
    review: 'nouns-1-review',
  },
  food1: {
    name: 'lesson-food-1',
    stage1: 'food-1-1',
    stage2: 'food-1-2',
    stage3: 'food-1-3',
    stage4: 'food-1-4',
    review: 'food-1-review',
  },
  adjectives1: {
    name: 'lesson-adjectives-1',
    stage1: 'adjectives-1-1',
    stage2: 'adjectives-1-2',
    stage3: 'adjectives-1-3',
    stage4: 'adjectives-1-4',
    review: 'adjectives-1-review',
  },
  verbs1: {
    name: 'lesson-verbs-1',
    stage1: 'verbs-1-1',
    stage2: 'verbs-1-2',
    stage3: 'verbs-1-3',
    stage4: 'verbs-1-4',
    review: 'verbs-1-review',
  },
  nouns2: {
    name: 'lesson-nouns-2',
    stage1: 'nouns-2-1',
    stage2: 'nouns-2-2',
    review: 'nouns-2-review',
  },
  aroundTheHouse: {
    name: 'lesson-around-the-house',
    stage1: 'around-the-house-1',
    stage2: 'around-the-house-2',
    stage3: 'around-the-house-3',
    stage4: 'around-the-house-4',
    stage5: 'around-the-house-5',
    review: 'around-the-house-review',
  },
  school: {
    name: 'lesson-school',
    stage1: 'school-1',
    stage2: 'school-2',
    stage3: 'school-3',
    stage4: 'school-4',
    stage5: 'school-5',
    review: 'school-review',
  },
  office: {
    name: 'lesson-office',
    stage1: 'office-1',
    stage2: 'office-2',
    stage3: 'office-3',
    stage4: 'office-4',
    stage5: 'office-5',
    review: 'office-review',
  },
  whenAndWhere: {
    name: 'lesson-when-and-where',
    stage1: 'when-and-where-1',
    stage2: 'when-and-where-2',
    stage3: 'when-and-where-3',
    stage4: 'when-and-where-4',
    review: 'when-and-where-review',
  },
  nature: {
    name: 'lesson-nature',
    stage1: 'nature-1',
    stage2: 'nature-2',
    stage3: 'nature-3',
    stage4: 'nature-4',
    review: 'nature-review',
  },
  bodyAndHealth: {
    name: 'lesson-body-and-health',
    stage1: 'body-and-health-1',
    stage2: 'body-and-health-2',
    stage3: 'body-and-health-3',
    stage4: 'body-and-health-4',
    stage5: 'body-and-health-5',
    review: 'body-and-health-review',
  },
  animals: {
    name: 'lesson-animals',
    stage1: 'animals-1',
    stage2: 'animals-2',
    stage3: 'animals-3',
    stage4: 'animals-4',
    stage5: 'animals-5',
    review: 'animals-review',
  },
  science: {
    name: 'lesson-science',
    stage1: 'science-1',
    stage2: 'science-2',
    stage3: 'science-3',
    stage4: 'science-4',
    stage5: 'science-5',
    review: 'science-review',
  },
};
