export default {
  basicVocab: {
    name: 'lesson-basic-vocab',
    stage1: 'basic-vocab-1',
    stage2: 'basic-vocab-2',
    stage3: 'basic-vocab-3',
    stage4: 'basic-vocab-4',
    review: 'basic-vocab-review',
  },
  numbers1: {
    name: 'lesson-numbers-1',
    stage1: 'numbers-1-1',
    stage2: 'numbers-1-2',
    stage3: 'numbers-1-3',
    review: 'numbers-1-review',
  },
  nouns1: {
    name: 'lesson-nouns-1',
    stage1: 'nouns-1-1',
    stage2: 'nouns-1-2',
    stage3: 'nouns-1-3',
    review: 'nouns-1-review',
  },
  food1: {
    name: 'lesson-food-1',
    stage1: 'food-1-1',
    stage2: 'food-1-2',
    stage3: 'food-1-3',
    stage4: 'food-1-4',
    review: 'food-1-review',
  },
  adjectives1: {
    name: 'lesson-adjectives-1',
    stage1: 'adjectives-1-1',
    stage2: 'adjectives-1-2',
    stage3: 'adjectives-1-3',
    stage4: 'adjectives-1-4',
    review: 'adjectives-1-review',
  },
  verbs1: {
    name: 'lesson-verbs-1',
    stage1: 'verbs-1-1',
    stage2: 'verbs-1-2',
    stage3: 'verbs-1-3',
    stage4: 'verbs-1-4',
    review: 'verbs-1-review',
  },
  nouns2: {
    name: 'lesson-nouns-2',
    stage1: 'nouns-2-1',
    stage2: 'nouns-2-2',
    review: 'nouns-2-review',
  },
  aroundTheHouse: {
    name: 'lesson-around-the-house',
    stage1: 'around-the-house-1',
    stage2: 'around-the-house-2',
    stage3: 'around-the-house-3',
    stage4: 'around-the-house-4',
    stage5: 'around-the-house-5',
    review: 'around-the-house-review',
  },
};
