export default {
  demo: {
    name: 'lesson-demo',
    stage1: 'demo-1',
  },
  basicVocab: {
    name: 'lesson-basic-vocab',
    stage1: 'basic-vocab-1',
    stage2: 'basic-vocab-2',
    stage3: 'basic-vocab-3',
    stage4: 'basic-vocab-4',
    review: 'basic-vocab-review',
  },
  numbers1: {
    name: 'lesson-numbers-1',
    stage1: 'numbers-1-1',
    stage2: 'numbers-1-2',
    stage3: 'numbers-1-3',
    review: 'numbers-1-review',
  },
  nouns1: {
    name: 'lesson-nouns-1',
    stage1: 'nouns-1-1',
    stage2: 'nouns-1-2',
    stage3: 'nouns-1-3',
    review: 'nouns-1-review',
  },
  food1: {
    name: 'lesson-food-1',
    stage1: 'food-1-1',
    stage2: 'food-1-2',
    stage3: 'food-1-3',
    review: 'food-1-review',
  },
  adjectives1: {
    name: 'lesson-adjectives-1',
    stage1: 'adjectives-1-1',
    stage2: 'adjectives-1-2',
    stage3: 'adjectives-1-3',
    review: 'adjectives-1-review',
  },
  verbs1: {
    name: 'lesson-verbs-1',
    stage1: 'verbs-1-1',
    stage2: 'verbs-1-2',
    stage3: 'verbs-1-3',
    review: 'verbs-1-review',
  },
  nouns2: {
    name: 'lesson-nouns-2',
    stage1: 'nouns-2-1',
    stage2: 'nouns-2-2',
    stage3: 'nouns-2-3',
    stage4: 'nouns-2-4',
    review: 'nouns-2-review',
  },
  aroundTheHouse1: {
    name: 'lesson-around-the-house-1',
    stage1: 'around-the-house-1-1',
    stage2: 'around-the-house-1-2',
    stage3: 'around-the-house-1-3',
    review: 'around-the-house-1-review',
  },
  school1: {
    name: 'lesson-school-1',
    stage1: 'school-1-1',
    stage2: 'school-1-2',
    stage3: 'school-1-3',
    review: 'school-1-review',
  },
  office: {
    name: 'lesson-office',
    stage1: 'office-1',
    stage2: 'office-2',
    stage3: 'office-3',
    stage4: 'office-4',
    review: 'office-review',
  },
  whenAndWhere: {
    name: 'lesson-when-and-where',
    stage1: 'when-and-where-1',
    stage2: 'when-and-where-2',
    stage3: 'when-and-where-3',
    stage4: 'when-and-where-4',
    review: 'when-and-where-review',
  },
  nature1: {
    name: 'lesson-nature-1',
    stage1: 'nature-1-1',
    stage2: 'nature-1-2',
    stage3: 'nature-1-3',
    review: 'nature-1-review',
  },
  bodyAndHealth1: {
    name: 'lesson-body-and-health-1',
    stage1: 'body-and-health-1-1',
    stage2: 'body-and-health-1-2',
    stage3: 'body-and-health-1-3',
    review: 'body-and-health-1-review',
  },
  animals1: {
    name: 'lesson-animals-1',
    stage1: 'animals-1-1',
    stage2: 'animals-1-2',
    stage3: 'animals-1-3',
    review: 'animals-1-review',
  },
  science1: {
    name: 'lesson-science-1',
    stage1: 'science-1-1',
    stage2: 'science-1-2',
    stage3: 'science-1-3',
    review: 'science-1-review',
  },
  fashion1: {
    name: 'lesson-fashion-1',
    stage1: 'fashion-1-1',
    stage2: 'fashion-1-2',
    stage3: 'fashion-1-3',
    review: 'fashion-1-review',
  },
  ordinalNumbers: {
    name: 'lesson-ordinal-numbers',
    stage1: 'ordinal-numbers-1',
    stage2: 'ordinal-numbers-2',
    stage3: 'ordinal-numbers-3',
    review: 'ordinal-numbers-review',
  },
  verbs2: {
    name: 'lesson-verbs-2',
    stage1: 'verbs-2-1',
    stage2: 'verbs-2-2',
    stage3: 'verbs-2-3',
    stage4: 'verbs-2-4',
    review: 'verbs-2-review',
  },
  food2: {
    name: 'lesson-food-2',
    stage1: 'food-2-1',
    stage2: 'food-2-2',
    stage3: 'food-2-3',
    stage4: 'food-2-4',
    review: 'food-2-review',
  },
  aroundTheHouse2: {
    name: 'lesson-around-the-house-2',
    stage1: 'around-the-house-2-1',
    stage2: 'around-the-house-2-2',
    stage3: 'around-the-house-2-3',
    stage4: 'around-the-house-2-4',
    review: 'around-the-house-2-review',
  },
  school2: {
    name: 'lesson-school-2',
    stage1: 'school-2-1',
    stage2: 'school-2-2',
    stage3: 'school-2-3',
    review: 'school-2-review',
  },
  nature2: {
    name: 'lesson-nature-2',
    stage1: 'nature-2-1',
    stage2: 'nature-2-2',
    stage3: 'nature-2-3',
    review: 'nature-2-review',
  },
  bodyAndHealth2: {
    name: 'lesson-body-and-health-2',
    stage1: 'body-and-health-2-1',
    stage2: 'body-and-health-2-2',
    stage3: 'body-and-health-2-3',
    review: 'body-and-health-2-review',
  },
  animals2: {
    name: 'lesson-animals-2',
    stage1: 'animals-2-1',
    stage2: 'animals-2-2',
    stage3: 'animals-2-3',
    review: 'animals-2-review',
  },
  science2: {
    name: 'lesson-science-2',
    stage1: 'science-2-1',
    stage2: 'science-2-2',
    stage3: 'science-2-3',
    review: 'science-2-review',
  },
  fashion2: {
    name: 'lesson-fashion-2',
    stage1: 'fashion-2-1',
    stage2: 'fashion-2-2',
    stage3: 'fashion-2-3',
    stage4: 'fashion-2-4',
    review: 'fashion-2-review',
  },
  food3: {
    name: 'lesson-food-3',
    stage1: 'food-3-1',
    stage2: 'food-3-2',
    stage3: 'food-3-3',
    stage4: 'food-3-4',
    review: 'food-3-review',
  },
  food4: {
    name: 'lesson-food-4',
    stage1: 'food-4-1',
    stage2: 'food-4-2',
    stage3: 'food-4-3',
    stage4: 'food-4-4',
    review: 'food-4-review',
  },
  adverbs1: {
    name: 'lesson-adverbs-1',
    stage1: 'adverbs-1-1',
    stage2: 'adverbs-1-2',
    stage3: 'adverbs-1-3',
    review: 'adverbs-1-review',
  },
  adverbs2: {
    name: 'lesson-adverbs-2',
    stage1: 'adverbs-2-1',
    stage2: 'adverbs-2-2',
    stage3: 'adverbs-2-3',
    review: 'adverbs-2-review',
  },
  adjectives2: {
    name: 'lesson-adjectives-2',
    stage1: 'adjectives-2-1',
    stage2: 'adjectives-2-2',
    stage3: 'adjectives-2-3',
    stage4: 'adjectives-2-4',
    review: 'adjectives-2-review',
  },
  adjectives3: {
    name: 'lesson-adjectives-3',
    stage1: 'adjectives-3-1',
    stage2: 'adjectives-3-2',
    stage3: 'adjectives-3-3',
    stage4: 'adjectives-3-4',
    review: 'adjectives-3-review',
  },
  verbs3: {
    name: 'lesson-verbs-3',
    stage1: 'verbs-3-1',
    stage2: 'verbs-3-2',
    stage3: 'verbs-3-3',
    stage4: 'verbs-3-4',
    review: 'verbs-3-review',
  },
  verbs4: {
    name: 'lesson-verbs-4',
    stage1: 'verbs-4-1',
    stage2: 'verbs-4-2',
    stage3: 'verbs-4-3',
    stage4: 'verbs-4-4',
    review: 'verbs-4-review',
  },
  verbs5: {
    name: 'lesson-verbs-5',
    stage1: 'verbs-5-1',
    stage2: 'verbs-5-2',
    stage3: 'verbs-5-3',
    stage4: 'verbs-5-4',
    stage5: 'verbs-5-5',
    review: 'verbs-5-review',
  },
  nouns3: {
    name: 'lesson-nouns-3',
    stage1: 'nouns-3-1',
    stage2: 'nouns-3-2',
    stage3: 'nouns-3-3',
    stage4: 'nouns-3-4',
    review: 'nouns-3-review',
  },
  nouns4: {
    name: 'lesson-nouns-4',
    stage1: 'nouns-4-1',
    stage2: 'nouns-4-2',
    stage3: 'nouns-4-3',
    stage4: 'nouns-4-4',
    review: 'nouns-4-review',
  },
  nouns5: {
    name: 'lesson-nouns-5',
    stage1: 'nouns-5-1',
    stage2: 'nouns-5-2',
    stage3: 'nouns-5-3',
    stage4: 'nouns-5-4',
    stage5: 'nouns-5-5',
    review: 'nouns-5-review',
  },
  travel: {
    name: 'lesson-travel',
    stage1: 'travel-1',
    stage2: 'travel-2',
    stage3: 'travel-3',
    review: 'travel-review',
  },
  sports: {
    name: 'lesson-sports',
    stage1: 'sports-1',
    stage2: 'sports-2',
    stage3: 'sports-3',
    review: 'sports-review',
  },
  toolsAndHardware: {
    name: 'lesson-tools-and-hardware',
    stage1: 'tools-and-hardware-1',
    stage2: 'tools-and-hardware-2',
    stage3: 'tools-and-hardware-3',
    review: 'tools-and-hardware-review',
  },
  nouns6: {
    name: 'lesson-nouns-6',
    stage1: 'nouns-6-1',
    stage2: 'nouns-6-2',
    stage3: 'nouns-6-3',
    stage4: 'nouns-6-4',
    stage5: 'nouns-6-5',
    review: 'nouns-6-review',
  },
  nouns7: {
    name: 'lesson-nouns-7',
    stage1: 'nouns-7-1',
    stage2: 'nouns-7-2',
    stage3: 'nouns-7-3',
    stage4: 'nouns-7-4',
    stage5: 'nouns-7-5',
    review: 'nouns-7-review',
  },
  nouns8: {
    name: 'lesson-nouns-8',
    stage1: 'nouns-8-1',
    stage2: 'nouns-8-2',
    stage3: 'nouns-8-3',
    stage4: 'nouns-8-4',
    stage5: 'nouns-8-5',
    review: 'nouns-8-review',
  },
  nouns9: {
    name: 'lesson-nouns-9',
    stage1: 'nouns-9-1',
    stage2: 'nouns-9-2',
    stage3: 'nouns-9-3',
    stage4: 'nouns-9-4',
    stage5: 'nouns-9-5',
    review: 'nouns-9-review',
  },
};
