export default {
  waves: [
    {
      baseSpawnRate: 1000,
      spawnRange: 250,
      start: 0,
      maxStart: 15,
      maxEnd: 60,
      end: 60,
    },
    {
      baseSpawnRate: 1250,
      spawnRange: 200,
      start: 60,
      maxStart: 80,
      maxEnd: 100,
      end: 120,
    },
    {
      baseSpawnRate: 1000,
      spawnRange: 150,
      start: 120,
      maxStart: 140,
      maxEnd: 160,
      end: 180,
    },
  ],
  maxHealth: 20,
  startHealth: 20,
  baseFallSpeed: 125,
  fallRange: 10,
  gameTime: 180,
  zombieColumns: 18,
  sidePaddingPercent: 20,
  maxTextEntry: 22,
  splatterBase: -5,
  splatterRange: 8,
  splatterVarieties: 6,
  damageFlashDuration: 100,
  damageFlashColor: { red: 180, green: 15, blue: 15 },
  damageShakeDuration: 200,
  damageShakeIntensity: 0.005,
  statusTime: 1500,
  fonts: {
    killSize: 22,
    killFill: '#ffffff',
    cashSize: 22,
    cashFill: '#ffffff',
    timerSize: 22,
    timerFill: '#ffffff',
    zombieSize: 10,
    zombieFill: '#ffffff',
    textEntrySize: 18,
    textEntryFill: '#ffffff',
    statusSize: 14,
    statusEntryFill: '#ffffff',
  },
  ui: {
    textEntryStyle: { color: '#000000' },
    zombieWordBgStyle: { color: '#000000' },
    zombieWordBgPadding: 2,
    hudHeight: 120,
    hudBufferHeight: 70,
  },
  statusMessages: {
    damage: 'Cerebros\nricos!',
  },
};
