export default {
  mapTitleText: 'Choose a Location',
  stageTitleText: 'Choose a Stage',
  screenFadeTime: 750,
  ui: {
    borderColor: 0xffffff,
    borderWidth: 5,
    squareWidth: 10,
    mapGridWidth: 3,
    mapGridColor: 0x222222,
    borderDisableColor: 0x222222,
    mapPinCellWidth: 0.25,
    requirementLineWidth: 3,
    requirementLineColor: 0xffffff,
  },
  modals: {
    start: [
      'This here\'s the town map. From here',
      'ya can see all the places ya\'ve cleared',
      'out along with the all the spots that are',
      'still infested. Yer gonna hafta clear',
      'out each location in stages. Once ya pick',
      'a location on the map ya can pick which',
      'stage to tackle. Them zombies don\'t much',
      'care fer bein\' forcibly removed, so ya',
      'should expect each location to end with',
      'one last assault from them things.',
      'Ya might call it a \'Review\', heh!',
      '',
      'I\'ll go ahead and mark the areas on yer',
      'map as ya clear \'em out. But fair warnin\',',
      'these zombies are wily. They\'ll try to',
      'sneak back in any way they can. Don\'t be',
      'surprised if ya see zombies from one location',
      'poppin\' up in other parts of town. And',
      'sometimes ya might just have to go back and',
      'clear out zombies from an area ya',
      'already captured.',
      '',
      'Well, that\'s enough ramblin\' from me.',
      'Let\'s get started!',
    ],
    reviewLocked: [
      'Whoa! Hold up there, friend.',
      'You can\'t just charge into the review stage',
      'guns blazin\'. Yer gonna have to clear out',
      'all them other stages first.',
    ],
    lessonLocked: [
      'Whoa! Slow down! That area\'s still too',
      'dangerous. You\'ll never make it there alive!',
      'I marked the spots we can get to in yella on',
      'yer map. Stick to those!',
    ],
  },
  choiceModals: {
    stageSelected: {
      text: ['Are ya ready to start?', '', 'Or do ya need some target practice first?'],
      choices: [
        'Start Game',
        'Target Practice',
      ],
    },
    clearedStageSelected: {
      text: [
        'You already cleared this stage!',
        '',
        'But there might still be some zombies',
        'around if you want to check it out.'],
      choices: [
        'Start Game',
        'Target Practice',
      ],
    },
    reviewStageSelected: {
      text: [
        'Alright, friend, this is the big one.', 'The final push to clear out this location',
        'Yer gonna see vocab from every stage in this lesson.', 'I sure hope yer ready.',
      ],
      choices: [
        'Start Game',
      ],
    },
    clearedReviewStageSelected: {
      text: [
        'You already cleared this whole area,',
        'but it\'s a good idea to check back in.',
        '',
        'I\'m sure there\'s still some zombies around,',
        'and more practice never hurt.',
      ],
      choices: [
        'Start Game',
      ],
    },
  },
  statusMessages: {
    instructions: [
      'Arrows to move',
      '',
      '',
      'Space/Enter to choose',
      '',
      '',
      'Esc to go back',
    ],
  },
  fonts: {
    instructionsSize: 11,
    instructionsFill: '#ffffff',
    mapTitleSize: 14,
    mapTitleFill: '#ffffff',
    mapLocationSize: 14,
    mapLocationFill: '#ffffff',
    lessonInfoTitleSize: 16,
    lessonInfoTitleColor: 0xffff22,
    lessonInfoTextSize: 11,
    lessonInfoTextFill: '#ffffff',
    stageTitleSize: 14,
    stageTitleFill: '#ffffff',
    stageInfoTitleSize: 14,
    stageInfoTitleFill: '#ffffff',
    stageInfoTypeSize: 18,
    stageInfoTypeColor: 0xffff22,
    stageInfoSubtitleSize: 11,
    stageInfoSubtitleFill: '#ffffff',
  },
};
