export default {
  screenFadeTime: 750,
  practiceWordBuffer: 1250,
  fonts: {
    vocabSize: 11,
    vocabSizeSmall: 8,
    dotSize: 9,
    vocabFill: '#ffffff',
    menuOptionSize: 11,
    menuOptionFill: '#ffffff',
    practiceWordSize: 10,
    practiceWordFill: '#ffffff',
    practiceWordCorrectFill: '0x22dd22',
    practiceWordWrongFill: '0xdd2222',
  },
  ui: {
    practiceWordBgStyle: { color: '#000000' },
    practiceWordBgPadding: 2,
    textEntryStyle: { color: '#000000' },
    hudConfig: {
      weapon: false,
      item: false,
      health: false,
      kills: false,
      cash: false,
      timer: false,
      message: true,
      textInput: false,
      hudBuffer: true,
      handleInput: false,
    },
  },
  statusMessages: {
    start: [
      'Arrows to move',
      '',
      'Space/Enter',
      'to choose',
    ],
    practice: [
      'Type the translation',
      '',
      'Enter to shoot',
      'Esc to quit',
    ],
    hit: 'Nice shot!',
    miss: [
      'Missed!',
      'Try again!',
    ],
  },
  modals: {
    tutorial: [
      'Welcome to target practice, friend.',
      'You need to be prepared if yer gonna',
      'take on those zombies.',
      '',
      'Here\'s how it works: The words on the sides',
      'of the screen are the new vocab fer',
      'this stage. Memorize \'em!',
      '',
      'You can use the controls at the bottom',
      'to hide one language or the other',
      'if it helps you study.',
      '',
      'When yer ready to put yer skills to the test',
      'select \'Practice\'. I\'ll set up the bottles',
      'and you do yer best to shoot \'em down.',
      '',
      'Just type the translation fer the word under',
      'the bottle and press \'Enter\'. Don\'t worry',
      'about time and don\'t worry about missin\'.',
      '',
      'And if you get tired you can stop at',
      'any time by pressin\' \'Esc\'.',
    ],
    practice: [
      'I\'ll set up the bottles, then.',
      'Take yer time. And good luck.',
    ],
  },
};
