export default {
  screenFadeTime: 750,
  statusTime: 1500,
  fonts: {
    vocabSize: 11,
    vocabSizeSmall: 7,
    dotSize: 9,
    vocabFill: '#ffffff',
    menuOptionSize: 11,
    menuOptionFill: '#ffffff',
    practiceWordSize: 10,
    practiceWordFill: '#ffffff',
    practiceWordCorrectFill: '0x22dd22',
    practiceWordWrongFill: '0xdd2222',
  },
  ui: {
    practiceWordBgStyle: { color: '#000000' },
    practiceWordBgPadding: 2,
    textEntryStyle: { color: '#000000' },
    hudConfig: {
      weapon: false,
      item: false,
      health: false,
      kills: false,
      cash: false,
      timer: false,
      message: true,
      textInput: false,
      hudBuffer: true,
      handleInput: false,
    },
  },
  statusMessages: {
    hit: 'Nice shot!',
    miss: 'Keep trying!',
  },
};
